### PR TITLE
EIP-121: CONDITION → CONDITIONS

### PR DESCRIPTION
**Pull request by icrc-fdeniger**
Ticket: https://issues.openmrs.org/browse/EIP-121

### CODE REVIEW

**Comment by icrc-fdeniger** [comment]
@mks-d @wluyima Please can you review this PR ? I will need to integrate and change our End to end tests to check conditions tables are synchronized

**Comment by icrc-fdeniger** [comment]
_Note_: Bintray services are retired so I remove the configuration in the main pom.xml file

**Comment by icrc-fdeniger** [comment]
@mks-d @wluyima is this PR ok for you ?

**Review by mks-d — APPROVED** [review]
LGTM but @wluyima to merge.

**Review by wluyima — APPROVED** [review]

**Pull request merged**
